### Numpy 基本介紹

In [ ]:
import numpy as np
import pandas as pd
import matplotlib as mp


# 創建一個一維陣列，並指定元素為浮點數

a = np.array([1.5, 5.5, 9.5], dtype = 'float64')
print(type(a))

# 顯示元素型態
print(a.dtype)

print(a.max())

<class 'numpy.ndarray'>
float64
9.5


In [ ]:
# 創建一個二維矩陣，並指定元素為整數
b = np.array([[1, 5, 9], [2, 6, 10]], dtype = 'int64')

# 顯示矩陣形狀
print(b.shape)

(2, 3)


### 矩陣取值

In [ ]:
# 矩陣方向都是先列後行

print(b[0, 0])
print(b[0, 1])

# 第1列第2行是?

1
5


In [ ]:
# 創建一個三維矩陣，並指定元素為整數
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype = 'int64')

# 矩陣方向都是先列後行
print(c[0]) # 指定第0列
print(c[1]) # 指定第1列
print(c[2]) # 指定第2列

[1 2 3]
[4 5 6]
[7 8 9]


### 矩陣切片

In [ ]:
print(c[:, 0]) # 指定第0行,所有列
print(c[:, 1]) # 指定第1行,所有列
print(c[:, 2]) # 指定第2行,所有列

[1 4 7]
[2 5 8]
[3 6 9]


In [ ]:
print(c[:2, :2]) # 指定第0~1列，第0~1行

[[1 2]
 [4 5]]


In [ ]:
# 試切出第1列，第1~2行的元素
# c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype = 'int64')
# print(c[1, 1:3])

[5 6]


### 合併陣列

In [ ]:
#np.concatenate() 方法將兩個陣列合併
x = np.array([1, 2, 3]) 
y = np.array([4, 5, 6]) 

print(np.concatenate([x, y]))

[1 2 3 4 5 6]


### 矩陣重塑

In [ ]:
# np.reshape() 可以改變矩陣的形狀
arrayA = np.array([1,2,3,4,5,6,7,8])
arrayB = np.reshape(arrayA, (4,2)) #先列後行

print(arrayB)
print(arrayB.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


### 快速創建陣列or矩陣

In [ ]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
# 返回指定間隔內的均勻間隔的數字
x = np.linspace(1,3,5)
print(x)

[1.  1.5 2.  2.5 3. ]


In [ ]:
# numpy.zeros(shape, dtype=float, order='C')
# 返回給定形狀和類型的新數組，並用零填充。
x = np.zeros((2,2), dtype=int)
print(x)

[[0 0]
 [0 0]]


In [ ]:
# numpy.ones(shape, dtype=None, order='C')
# 返回給定形狀和類型的新數組，並填充為1。
x = np.ones(10, dtype=int)
print(x)

[1 1 1 1 1 1 1 1 1 1]
